name: .NET Build and Test

on:
  push:
    branches:
      - master
      - dev
      - feature/audio-handler
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # oder deine Zielversion

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test VirtualNvhAnalyzer.Infrastructure.Tests/VirtualNvhAnalyzer.Infrastructure.Tests.csproj --no-build --verbosity normal
